### ISSUE TITLE
Category drop down box does not show anything

### ISSUE THREAD

**Issue by luantran1311** [meanbee/magento-autocategories#1]
I have just noticed that the Category drop-down won't let me select any category http://prntscr.com/n2xc4v

**Comment by bobbyshaw** [comment]
That would suggest that this function isn't returning your category tree: https://github.com/meanbee/magento-autocategories/blob/master/src/app/code/community/Meanbee/AutoCategories/Model/System/Config/Source/Category.php#L8

I would check the logs in case there are any errors or warnings related to autocategories. 

Then, there's an assumption here that your root category has a parent ID of 0 - I've never seen this not to be true, but that would be one thing for you to check.

**Comment by luantran1311** [comment]
Since the root category ID from my store is 2, I will have a look then.
I emailed Meanbee support a week ago but no one answered, so I have to post the issue on Github.

**Comment by bobbyshaw** [comment]
I don't think the root category ID will matter, but it should have a parent_id of 0. 

The meanbee support email address isn't actively monitored any longer, we're now part of @space48. Once I saw that you'd created both, I decided just to respond on here.

**Comment by luantran1311** [comment]
Thank you @bobbyshaw .
The extension works fine for me now.

**Comment by bobbyshaw** [comment]
That's great. Would you be able to share what the solution was in case it's helpful for someone else?
